/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedShellRouteImport } from './routes/_authenticated._shell'
import { Route as AuthenticatedShellClassesRouteImport } from './routes/_authenticated._shell.classes'
import { Route as AuthenticatedShellDashboardRouteImport } from './routes/_authenticated._shell.dashboard'
import { Route as AuthenticatedShellDeveloperRouteImport } from './routes/_authenticated._shell.developer'
import { Route as AuthenticatedShellGradesRouteImport } from './routes/_authenticated._shell.grades'
import { Route as AuthenticatedShellIssueResultsRouteImport } from './routes/_authenticated._shell.issue-results'
import { Route as AuthenticatedShellReportsRouteImport } from './routes/_authenticated._shell.reports'
import { Route as AuthenticatedShellResultsRouteImport } from './routes/_authenticated._shell.results'
import { Route as AuthenticatedShellSectionsRouteImport } from './routes/_authenticated._shell.sections'
import { Route as AuthenticatedShellSettingsRouteImport } from './routes/_authenticated._shell.settings'
import { Route as AuthenticatedShellStudentsRouteImport } from './routes/_authenticated._shell.students'
import { Route as AuthenticatedShellSubjectsRouteImport } from './routes/_authenticated._shell.subjects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedShellRoute = AuthenticatedShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedShellClassesRoute =
  AuthenticatedShellClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDashboardRoute =
  AuthenticatedShellDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellDeveloperRoute =
  AuthenticatedShellDeveloperRouteImport.update({
    id: '/developer',
    path: '/developer',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellGradesRoute =
  AuthenticatedShellGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellIssueResultsRoute =
  AuthenticatedShellIssueResultsRouteImport.update({
    id: '/issue-results',
    path: '/issue-results',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellReportsRoute =
  AuthenticatedShellReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellResultsRoute =
  AuthenticatedShellResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSectionsRoute =
  AuthenticatedShellSectionsRouteImport.update({
    id: '/sections',
    path: '/sections',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSettingsRoute =
  AuthenticatedShellSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellStudentsRoute =
  AuthenticatedShellStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)
const AuthenticatedShellSubjectsRoute =
  AuthenticatedShellSubjectsRouteImport.update({
    id: '/subjects',
    path: '/subjects',
    getParentRoute: () => AuthenticatedShellRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/classes': typeof AuthenticatedShellClassesRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/developer': typeof AuthenticatedShellDeveloperRoute
  '/grades': typeof AuthenticatedShellGradesRoute
  '/issue-results': typeof AuthenticatedShellIssueResultsRoute
  '/reports': typeof AuthenticatedShellReportsRoute
  '/results': typeof AuthenticatedShellResultsRoute
  '/sections': typeof AuthenticatedShellSectionsRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/students': typeof AuthenticatedShellStudentsRoute
  '/subjects': typeof AuthenticatedShellSubjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/classes': typeof AuthenticatedShellClassesRoute
  '/dashboard': typeof AuthenticatedShellDashboardRoute
  '/developer': typeof AuthenticatedShellDeveloperRoute
  '/grades': typeof AuthenticatedShellGradesRoute
  '/issue-results': typeof AuthenticatedShellIssueResultsRoute
  '/reports': typeof AuthenticatedShellReportsRoute
  '/results': typeof AuthenticatedShellResultsRoute
  '/sections': typeof AuthenticatedShellSectionsRoute
  '/settings': typeof AuthenticatedShellSettingsRoute
  '/students': typeof AuthenticatedShellStudentsRoute
  '/subjects': typeof AuthenticatedShellSubjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_shell': typeof AuthenticatedShellRouteWithChildren
  '/_authenticated/_shell/classes': typeof AuthenticatedShellClassesRoute
  '/_authenticated/_shell/dashboard': typeof AuthenticatedShellDashboardRoute
  '/_authenticated/_shell/developer': typeof AuthenticatedShellDeveloperRoute
  '/_authenticated/_shell/grades': typeof AuthenticatedShellGradesRoute
  '/_authenticated/_shell/issue-results': typeof AuthenticatedShellIssueResultsRoute
  '/_authenticated/_shell/reports': typeof AuthenticatedShellReportsRoute
  '/_authenticated/_shell/results': typeof AuthenticatedShellResultsRoute
  '/_authenticated/_shell/sections': typeof AuthenticatedShellSectionsRoute
  '/_authenticated/_shell/settings': typeof AuthenticatedShellSettingsRoute
  '/_authenticated/_shell/students': typeof AuthenticatedShellStudentsRoute
  '/_authenticated/_shell/subjects': typeof AuthenticatedShellSubjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/reset-password'
    | '/classes'
    | '/dashboard'
    | '/developer'
    | '/grades'
    | '/issue-results'
    | '/reports'
    | '/results'
    | '/sections'
    | '/settings'
    | '/students'
    | '/subjects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/reset-password'
    | '/classes'
    | '/dashboard'
    | '/developer'
    | '/grades'
    | '/issue-results'
    | '/reports'
    | '/results'
    | '/sections'
    | '/settings'
    | '/students'
    | '/subjects'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/_shell'
    | '/_authenticated/_shell/classes'
    | '/_authenticated/_shell/dashboard'
    | '/_authenticated/_shell/developer'
    | '/_authenticated/_shell/grades'
    | '/_authenticated/_shell/issue-results'
    | '/_authenticated/_shell/reports'
    | '/_authenticated/_shell/results'
    | '/_authenticated/_shell/sections'
    | '/_authenticated/_shell/settings'
    | '/_authenticated/_shell/students'
    | '/_authenticated/_shell/subjects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_shell': {
      id: '/_authenticated/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedShellRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_shell/classes': {
      id: '/_authenticated/_shell/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedShellClassesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/dashboard': {
      id: '/_authenticated/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedShellDashboardRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/developer': {
      id: '/_authenticated/_shell/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof AuthenticatedShellDeveloperRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/grades': {
      id: '/_authenticated/_shell/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof AuthenticatedShellGradesRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/issue-results': {
      id: '/_authenticated/_shell/issue-results'
      path: '/issue-results'
      fullPath: '/issue-results'
      preLoaderRoute: typeof AuthenticatedShellIssueResultsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/reports': {
      id: '/_authenticated/_shell/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedShellReportsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/results': {
      id: '/_authenticated/_shell/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedShellResultsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/sections': {
      id: '/_authenticated/_shell/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof AuthenticatedShellSectionsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/settings': {
      id: '/_authenticated/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedShellSettingsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/students': {
      id: '/_authenticated/_shell/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedShellStudentsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
    '/_authenticated/_shell/subjects': {
      id: '/_authenticated/_shell/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AuthenticatedShellSubjectsRouteImport
      parentRoute: typeof AuthenticatedShellRoute
    }
  }
}

interface AuthenticatedShellRouteChildren {
  AuthenticatedShellClassesRoute: typeof AuthenticatedShellClassesRoute
  AuthenticatedShellDashboardRoute: typeof AuthenticatedShellDashboardRoute
  AuthenticatedShellDeveloperRoute: typeof AuthenticatedShellDeveloperRoute
  AuthenticatedShellGradesRoute: typeof AuthenticatedShellGradesRoute
  AuthenticatedShellIssueResultsRoute: typeof AuthenticatedShellIssueResultsRoute
  AuthenticatedShellReportsRoute: typeof AuthenticatedShellReportsRoute
  AuthenticatedShellResultsRoute: typeof AuthenticatedShellResultsRoute
  AuthenticatedShellSectionsRoute: typeof AuthenticatedShellSectionsRoute
  AuthenticatedShellSettingsRoute: typeof AuthenticatedShellSettingsRoute
  AuthenticatedShellStudentsRoute: typeof AuthenticatedShellStudentsRoute
  AuthenticatedShellSubjectsRoute: typeof AuthenticatedShellSubjectsRoute
}

const AuthenticatedShellRouteChildren: AuthenticatedShellRouteChildren = {
  AuthenticatedShellClassesRoute: AuthenticatedShellClassesRoute,
  AuthenticatedShellDashboardRoute: AuthenticatedShellDashboardRoute,
  AuthenticatedShellDeveloperRoute: AuthenticatedShellDeveloperRoute,
  AuthenticatedShellGradesRoute: AuthenticatedShellGradesRoute,
  AuthenticatedShellIssueResultsRoute: AuthenticatedShellIssueResultsRoute,
  AuthenticatedShellReportsRoute: AuthenticatedShellReportsRoute,
  AuthenticatedShellResultsRoute: AuthenticatedShellResultsRoute,
  AuthenticatedShellSectionsRoute: AuthenticatedShellSectionsRoute,
  AuthenticatedShellSettingsRoute: AuthenticatedShellSettingsRoute,
  AuthenticatedShellStudentsRoute: AuthenticatedShellStudentsRoute,
  AuthenticatedShellSubjectsRoute: AuthenticatedShellSubjectsRoute,
}

const AuthenticatedShellRouteWithChildren =
  AuthenticatedShellRoute._addFileChildren(AuthenticatedShellRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedShellRoute: typeof AuthenticatedShellRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedShellRoute: AuthenticatedShellRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
