import { pgEnum, pgTable, uuid, text, boolean, numeric, bigint, smallint, timestamp, unique, jsonb } from "drizzle-orm/pg-core";

export const appRole = pgEnum("app_role", ["admin", "moderator", "user"]);
export const schoolType = pgEnum("school_type", ["basic", "secondary", "mixed"]);
export const schoolStage = pgEnum("school_stage", ["basic", "secondary"]);
export const academicTerm = pgEnum("academic_term", ["first", "second", "final"]);
export const scoreTerm = pgEnum("score_term", ["first", "second"]);
export const resultPeriod = pgEnum("result_period", ["first", "second", "final"]);
export const resultTemplate = pgEnum("result_template", ["classic", "modern", "formal", "compact", "children_blue", "children_green", "children_orange", "formal_blue", "formal_green", "formal_gold"]);

export const schools = pgTable("schools", {
  id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), schoolType: schoolType("school_type").notNull().default("mixed"), region: text("region").notNull().default(""), ownerUserId: uuid("owner_user_id").notNull().unique(), examMax: numeric("exam_max").notNull().default("30"), courseworkMax: numeric("coursework_max").notNull().default("20"), termPassMark: numeric("term_pass_mark").notNull().default("25"), createdAt: timestamp("created_at",{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp("updated_at",{withTimezone:true}).notNull().defaultNow(),
});
export const profiles = pgTable("profiles", { userId: uuid("user_id").primaryKey(), schoolId: uuid("school_id").notNull().references(()=>schools.id), fullName:text("full_name").notNull(), phone:text("phone").notNull().default(""), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() });
export const userRoles = pgTable("user_roles", { id:uuid("id").primaryKey().defaultRandom(), userId:uuid("user_id").notNull(), role:appRole("role").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.userId,t.role)]);
export const academicYears = pgTable("academic_years", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), name:text("name").notNull(), isActive:boolean("is_active").notNull().default(false), isClosed:boolean("is_closed").notNull().default(false), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.schoolId,t.name)]);
export const gradeLevels = pgTable("grade_levels", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), academicYearId:uuid("academic_year_id").notNull().references(()=>academicYears.id), code:text("code").notNull(), name:text("name").notNull(), stage:schoolStage("stage").notNull(), sortOrder:smallint("sort_order").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.academicYearId,t.code),unique().on(t.id,t.schoolId)]);
export const sections = pgTable("sections", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), gradeLevelId:uuid("grade_level_id").notNull(), name:text("name").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.gradeLevelId,t.name),unique().on(t.id,t.schoolId)]);
export const students = pgTable("students", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), studentNumber:bigint("student_number",{mode:"number"}).notNull(), fullName:text("full_name").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow(), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.id,t.schoolId)]);
export const studentEnrollments = pgTable("student_enrollments", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), studentId:uuid("student_id").notNull(), academicYearId:uuid("academic_year_id").notNull().references(()=>academicYears.id), gradeLevelId:uuid("grade_level_id").notNull(), sectionId:uuid("section_id").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.studentId,t.academicYearId)]);
export const subjects = pgTable("subjects", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), gradeLevelId:uuid("grade_level_id").notNull(), name:text("name").notNull(), sortOrder:smallint("sort_order").notNull().default(1), createdAt:timestamp("created_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.gradeLevelId,t.name),unique().on(t.id,t.schoolId)]);
export const scores = pgTable("scores", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), academicYearId:uuid("academic_year_id").notNull().references(()=>academicYears.id), studentId:uuid("student_id").notNull(), subjectId:uuid("subject_id").notNull(), term:scoreTerm("term").notNull(), examScore:numeric("exam_score").default("0"), courseworkScore:numeric("coursework_score").default("0"), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.academicYearId,t.studentId,t.subjectId,t.term)]);
export const resultTemplateSettings = pgTable("result_template_settings", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), gradeLevelId:uuid("grade_level_id").notNull(), term:resultPeriod("term").notNull(), template:resultTemplate("template").notNull().default("formal_blue"), updatedAt:timestamp("updated_at",{withTimezone:true}).notNull().defaultNow() }, t=>[unique().on(t.gradeLevelId,t.term)]);
export const resultIssuances = pgTable("result_issuances", { id:uuid("id").primaryKey().defaultRandom(), schoolId:uuid("school_id").notNull().references(()=>schools.id), academicYearId:uuid("academic_year_id").notNull().references(()=>academicYears.id), gradeLevelId:uuid("grade_level_id").notNull(), sectionId:uuid("section_id"), term:resultPeriod("term").notNull(), template:resultTemplate("template").notNull(), resultsCount:smallint("results_count").notNull(), issuedBy:uuid("issued_by").notNull(), scope:text("scope").notNull().default("section"), snapshot:jsonb("snapshot").notNull().default({}), issuedAt:timestamp("issued_at",{withTimezone:true}).notNull().defaultNow() });
