import { createFileRoute } from "@tanstack/react-router";
import { BarChart3, CheckCircle2, Printer, Users, XCircle, Clock3 } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";
import { useResultData } from "@/hooks/useResultData";

export const Route=createFileRoute("/_authenticated._shell/reports")({head:()=>({meta:[{title:"التقارير | Md School"}]}),component:ReportsPage});
function ReportsPage(){
  const data=useResultData();
  const passed=data.results.filter(r=>r.complete&&r.passed).length;
  const failed=data.results.filter(r=>r.complete&&!r.passed).length;
  const incomplete=data.results.filter(r=>!r.complete).length;
  const completeResults=data.results.filter(r=>r.complete); const average=completeResults.length?completeResults.reduce((s,r)=>s+r.percentage,0)/completeResults.length:0;
  const subjectStats=data.subjects.map(subject=>{const vals=data.results.map(r=>r.subjectScores.find(x=>x.subject.id===subject.id));const complete=vals.filter(v=>v?.complete);const avg=complete.length?complete.reduce((s,v)=>s+(v?.score??0),0)/complete.length:0;const pass=complete.filter(v=>v?.passed).length;return{subject,avg,pass,fail:complete.length-pass,incomplete:vals.length-complete.length}});
  return <div className="space-y-6 print:p-0"><div className="print-hidden"><PageHeader title="التقارير" description="تقارير الطلاب والنجاح والرسوب وعدم اكتمال الدرجات ومتوسطات المواد والترتيب." actions={<Button variant="outline" onClick={()=>window.print()}><Printer className="size-4"/>طباعة التقرير</Button>}/></div>
    <Card className="print-hidden"><CardContent className="grid gap-3 pt-6 sm:grid-cols-4"><Select value={data.yearId} onValueChange={data.setYearId}><SelectTrigger><SelectValue placeholder="العام الدراسي"/></SelectTrigger><SelectContent>{data.years.map(y=><SelectItem key={y.id} value={y.id}>{y.name}{y.is_active?" — نشط":""}{y.is_closed?" — مغلق":""}</SelectItem>)}</SelectContent></Select><Select value={data.gradeId} onValueChange={data.setGradeId}><SelectTrigger><SelectValue placeholder="الصف"/></SelectTrigger><SelectContent>{data.activeGrades.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select><Select value={data.sectionId} onValueChange={v=>data.setSectionId(v==="all"?"":v)}><SelectTrigger><SelectValue placeholder="الشعبة (اختياري)"/></SelectTrigger><SelectContent><SelectItem value="all">كل الشعب</SelectItem>{data.sectionOptions.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Select value={data.period} onValueChange={v=>data.setPeriod(v as "first"|"second"|"final")}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="first">النصف الأول</SelectItem><SelectItem value="second">النصف الثاني</SelectItem><SelectItem value="final">النتيجة النهائية</SelectItem></SelectContent></Select></CardContent></Card>
    <div className="grid gap-4 sm:grid-cols-5"><Stat icon={Users} label="عدد الطلاب" value={data.results.length}/><Stat icon={CheckCircle2} label="الناجحون" value={passed}/><Stat icon={XCircle} label="الراسبون" value={failed}/><Stat icon={Clock3} label="غير مكتمل" value={incomplete}/><Stat icon={BarChart3} label="متوسط النسبة" value={Number(average.toFixed(1))}/></div>
    <Card><CardHeader><CardTitle>تقرير الطلاب</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>الترتيب</TableHead><TableHead>الطالب</TableHead><TableHead>المجموع</TableHead><TableHead>النسبة</TableHead><TableHead>الحالة</TableHead></TableRow></TableHeader><TableBody>{data.results.map(r=><TableRow key={r.student.id}><TableCell>{data.period === "first" && r.isTopFive?`${r.rank}${r.repeatedRank?" مكرر":""}`:"—"}</TableCell><TableCell className="font-medium">{r.student.full_name}</TableCell><TableCell>{r.total} / {r.maximum}</TableCell><TableCell>{r.percentage.toFixed(1)}%</TableCell><TableCell><Badge variant={!r.complete?"secondary":r.passed?"default":"destructive"}>{!r.complete?"غير مكتمل":r.passed?"ناجح":"راسب"}</Badge></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Card><CardHeader><CardTitle>تقرير المواد</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>المادة</TableHead><TableHead>المتوسط</TableHead><TableHead>ناجحون</TableHead><TableHead>راسبون</TableHead><TableHead>غير مكتمل</TableHead></TableRow></TableHeader><TableBody>{subjectStats.map(s=><TableRow key={s.subject.id}><TableCell>{s.subject.name}</TableCell><TableCell>{s.avg.toFixed(1)}</TableCell><TableCell>{s.pass}</TableCell><TableCell>{s.fail}</TableCell><TableCell>{s.incomplete}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>
    <Card><CardHeader><CardTitle>ملخص الشعب</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>الشعبة</TableHead><TableHead>الطلاب</TableHead><TableHead>متوسط النسبة</TableHead><TableHead>ناجحون</TableHead><TableHead>راسبون</TableHead><TableHead>غير مكتمل</TableHead></TableRow></TableHeader><TableBody>{Array.from(new Set(data.results.map(r=>r.student.section_name||"غير محدد"))).map(section=>{const rows=data.results.filter(r=>(r.student.section_name||"غير محدد")===section);const complete=rows.filter(r=>r.complete);return <TableRow key={section}><TableCell>{section}</TableCell><TableCell>{rows.length}</TableCell><TableCell>{complete.length?(complete.reduce((sum,r)=>sum+r.percentage,0)/complete.length).toFixed(1):"0.0"}</TableCell><TableCell>{rows.filter(r=>r.complete&&r.passed).length}</TableCell><TableCell>{rows.filter(r=>r.complete&&!r.passed).length}</TableCell><TableCell>{rows.filter(r=>!r.complete).length}</TableCell></TableRow>})}</TableBody></Table></CardContent></Card>
  </div>
}
function Stat({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <Card><CardContent className="flex items-center gap-4 pt-6"><span className="flex size-11 items-center justify-center rounded-lg bg-secondary text-brand-blue"><Icon className="size-5"/></span><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-bold">{value}</p></div></CardContent></Card>}
