import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Fingerprint, KeyRound, Pencil, Plus, Save, Trash2, UserRound } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader"; import { Button } from "@/components/ui/button"; import { Card,CardContent,CardHeader,CardTitle } from "@/components/ui/card"; import { Input } from "@/components/ui/input"; import { Field } from "@/components/common/FormSection"; import { useSchool } from "@/contexts/SchoolContext"; import { supabase } from "@/integrations/supabase/client"; import { toast } from "sonner";
import { friendlySupabaseError } from "@/lib/supabase-errors";
import { type ResultTemplate } from "@/lib/result-templates";
import { ResultTemplatePicker } from "@/components/results/ResultTemplatePicker";
export const Route=createFileRoute("/_authenticated/_shell/settings")({head:()=>({meta:[{title:"الإعدادات | Md School"}]}),component:SettingsPage});
type Year={id:string;name:string;is_active:boolean;is_closed:boolean};
function SettingsPage(){const{school,activeYear,years,grades,refresh}=useSchool();const[form,setForm]=useState({name:"",region:"",examMax:30,courseworkMax:20,passMark:25});const[username,setUsername]=useState("");const[newUsername,setNewUsername]=useState("");const[currentPassword,setCurrentPassword]=useState("");const[savingUsername,setSavingUsername]=useState(false);const[passkeyLoading,setPasskeyLoading]=useState(false);const[passkeys,setPasskeys]=useState<Array<{id:string;friendly_name?:string;created_at:string}>>([]);const[yearName,setYearName]=useState("");const[editYearId,setEditYearId]=useState("");const[templates,setTemplates]=useState<Record<string,ResultTemplate>>({});
 useEffect(()=>{if(school)setForm({name:school.name,region:school.region,examMax:school.exam_max,courseworkMax:school.coursework_max,passMark:school.term_pass_mark})},[school]);
 useEffect(()=>{void(async()=>{const{data}=await supabase.rpc("get_my_username");if(data){setUsername(data);setNewUsername(data)}try{const{data:keys}=await supabase.auth.passkey.list();setPasskeys((keys??[]).map(k=>({id:k.id,friendly_name:k.friendly_name,created_at:k.created_at})))}catch{setPasskeys([])}})()},[]);
 useEffect(()=>{void(async()=>{if(!school)return;const{data}=await supabase.from("result_template_settings").select("grade_level_id,term,template").eq("school_id",school.id);const next:Record<string,ResultTemplate>={};for(const r of data??[])next[`${r.grade_level_id}:${r.term}`]=r.template as ResultTemplate;setTemplates(next as Record<string,ResultTemplate>)})()},[school?.id]);
 const set=(key:keyof typeof form,value:string|number)=>setForm(c=>({...c,[key]:value}));
 async function save(){if(!school)return;const total=form.examMax+form.courseworkMax;if(form.examMax<1||form.courseworkMax<0||form.passMark<1||form.passMark>total){toast.error("تحقق من حدود الدرجات");return}const{error}=await supabase.from("schools").update({name:form.name.trim(),region:form.region.trim(),exam_max:form.examMax,coursework_max:form.courseworkMax,term_pass_mark:form.passMark}).eq("id",school.id);if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم حفظ الإعدادات");await refresh()}}
 async function saveUsername(){const value=newUsername.trim().toLowerCase();if(value===username)return;if(!/^[a-z0-9_]{3,32}$/.test(value)){toast.error("اسم المستخدم يجب أن يكون من 3 إلى 32 حرفًا: أحرف إنجليزية وأرقام وشرطة سفلية فقط");return}if(!currentPassword){toast.error("أدخل كلمة المرور الحالية للتأكيد");return}setSavingUsername(true);const{data,error}=await supabase.functions.invoke("change-username",{body:{username:value,currentPassword}});setSavingUsername(false);if(error)toast.error(error.message);else if(data?.error)toast.error(data.error);else{setUsername(data.username??value);setNewUsername(data.username??value);setCurrentPassword("");toast.success("تم تغيير اسم المستخدم")}}
 async function registerPasskey(){if(!window.isSecureContext){toast.error("الدخول السريع يحتاج إلى HTTPS أو localhost");return}setPasskeyLoading(true);const{error}=await supabase.auth.registerPasskey();if(!error){const{data:keys}=await supabase.auth.passkey.list();setPasskeys((keys??[]).map(k=>({id:k.id,friendly_name:k.friendly_name,created_at:k.created_at})));toast.success("تم تفعيل الدخول السريع على هذا الجهاز")}else toast.error("تعذر تفعيل الدخول السريع. تحقق من إعداد Passkeys في Supabase.");setPasskeyLoading(false)}
 async function yearSave(){if(!school||!yearName.trim()){toast.error("اكتب اسم العام الدراسي");return}if(editYearId){const{error}=await supabase.from("academic_years").update({name:yearName.trim()}).eq("id",editYearId);if(error)toast.error(friendlySupabaseError(error));else toast.success("تم تعديل العام")}else{const{error}=await supabase.rpc("create_academic_year",{p_name:yearName.trim(),p_copy_grades:true});if(error)toast.error(friendlySupabaseError(error));else toast.success("تم إنشاء العام مع نسخ الصفوف والمواد")}setYearName("");setEditYearId("");await refresh()}
 async function activate(id:string){const{error}=await supabase.rpc("set_active_academic_year",{p_year_id:id});if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم تفعيل العام الدراسي");await refresh()}} async function closeYear(id:string){const{error}=await supabase.rpc("close_academic_year",{p_year_id:id});if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم إغلاق العام الدراسي وحمايته من تعديل الدرجات");await refresh()}} async function reopenYear(id:string){const{error}=await supabase.rpc("reopen_academic_year",{p_year_id:id});if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم فتح العام الدراسي");await refresh()}}
 async function deleteYear(id:string){const{error}=await supabase.rpc("delete_academic_year",{p_year_id:id});if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم حذف العام");await refresh()}}
 async function saveTemplate(gradeId:string,term:"first"|"second"|"final"){const value=templates[`${gradeId}:${term}`]??"formal_blue";const{error}=await supabase.rpc("save_result_template",{p_grade_id:gradeId,p_term:term,p_template:value});if(error)toast.error(friendlySupabaseError(error));else toast.success("تم حفظ قالب الصف والفترة")}
 return <div className="space-y-6"><PageHeader title="الإعدادات" description="إدارة المدرسة والأعوام والحساب وقواعد النجاح والقوالب." actions={<Button onClick={save}><Save className="size-4"/>حفظ</Button>}/>
 <Card><CardHeader><CardTitle>بيانات المدرسة وقواعد الدرجات</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Field label="اسم المدرسة الرسمي" htmlFor="school-name"><Input id="school-name" value={form.name} onChange={e=>set("name",e.target.value)}/></Field><Field label="المحافظة / المديرية" htmlFor="region"><Input id="region" value={form.region} onChange={e=>set("region",e.target.value)}/></Field><Field label="درجة الاختبار" htmlFor="exam"><Input id="exam" type="number" min={1} value={form.examMax} onChange={e=>set("examMax",Number(e.target.value))}/></Field><Field label="درجة المحصلة" htmlFor="course"><Input id="course" type="number" min={0} value={form.courseworkMax} onChange={e=>set("courseworkMax",Number(e.target.value))}/></Field><Field label="حد النجاح للفترة" htmlFor="pass"><Input id="pass" type="number" min={1} value={form.passMark} onChange={e=>set("passMark",Number(e.target.value))}/></Field><p className="text-sm text-muted-foreground sm:col-span-2">الدرجة الكلية للفترة: {form.examMax+form.courseworkMax} — حد النجاح النهائي: {form.passMark*2}</p></CardContent></Card>
 <Card><CardHeader><CardTitle>إدارة الأعوام الدراسية</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex gap-2"><Input value={yearName} onChange={e=>setYearName(e.target.value)} placeholder="مثال: 1448 / 1449 هـ"/><Button onClick={yearSave}><Plus className="size-4"/>{editYearId?"حفظ التعديل":"إضافة عام"}</Button></div><div className="divide-y rounded-xl border">{years.map((y:Year)=><div key={y.id} className="flex items-center justify-between gap-3 p-3"><div><b>{y.name}</b>{y.is_active&&<span className="mr-2 text-sm text-brand-blue">النشط</span>}{y.is_closed&&<span className="mr-2 text-sm text-muted-foreground">مغلق</span>}</div><div className="flex gap-1"><Button variant="ghost" size="icon" onClick={()=>{setEditYearId(y.id);setYearName(y.name)}}><Pencil className="size-4"/></Button>{!y.is_closed&&!y.is_active&&<Button variant="outline" size="sm" onClick={()=>void activate(y.id)}>تفعيل</Button>} {y.is_closed?<Button variant="outline" size="sm" onClick={()=>void reopenYear(y.id)}>فتح</Button>:<Button variant="ghost" size="sm" onClick={()=>void closeYear(y.id)}>إغلاق</Button>} {!y.is_active&&!y.is_closed&&<Button variant="ghost" size="icon" onClick={()=>void deleteYear(y.id)}><Trash2 className="size-4"/></Button>}</div></div>)}</div></CardContent></Card>
 <Card><CardHeader><CardTitle>قوالب النتائج حسب الصف والفترة</CardTitle><p className="text-sm text-muted-foreground">ستة قوالب رسمية معتمدة: ثلاثة للأطفال وثلاثة رسمية. اللون الثالث للأطفال والرسمي ذهبي/برونزي بدل الوردي أو البنفسجي.</p></CardHeader><CardContent className="space-y-3">{grades.filter(g=>g.academic_year_id===activeYear?.id).map(g=><div key={g.id} className="grid items-center gap-2 rounded-xl border p-3 lg:grid-cols-[160px_1fr_1fr_1fr]"><b>{g.name}</b>{(["first","second","final"] as const).map(term=><div key={term} className="flex flex-col gap-2"><span className="text-xs font-semibold text-muted-foreground">{term==="first"?"النصف الأول":term==="second"?"النصف الثاني":"النتيجة النهائية"}</span><ResultTemplatePicker value={templates[`${g.id}:${term}`]??"formal_blue"} onChange={(value)=>setTemplates(c=>({...c,[`${g.id}:${term}`]:value}))}/><Button size="sm" variant="outline" onClick={()=>void saveTemplate(g.id,term)}>حفظ {term==="first"?"الأول":term==="second"?"الثاني":"النهائي"}</Button></div>)}</div>)}</CardContent></Card>
 <Card><CardHeader><CardTitle>حساب المدير</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="اسم المستخدم الحالي" htmlFor="current-username"><div className="relative"><UserRound className="pointer-events-none absolute end-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input id="current-username" value={username} disabled className="pe-10"/></div></Field><Field label="اسم المستخدم الجديد" htmlFor="new-username"><Input id="new-username" value={newUsername} onChange={e=>setNewUsername(e.target.value.toLowerCase())} maxLength={32}/></Field></div><Field label="كلمة المرور الحالية للتأكيد" htmlFor="current-password"><Input id="current-password" type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} autoComplete="current-password"/></Field><div className="flex justify-end"><Button onClick={saveUsername} disabled={savingUsername||newUsername===username}>{savingUsername?"جارٍ التحقق...":"تغيير اسم المستخدم"}</Button></div></CardContent></Card>
 <Card><CardHeader><CardTitle className="flex items-center gap-2"><Fingerprint className="size-5"/>الدخول السريع</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-muted-foreground">البصمة أو قفل الجهاز. يمكنك تسجيل أكثر من جهاز، وتبقى كلمة المرور خيارًا احتياطيًا.</p>{passkeys.length>0&&<div className="rounded-xl border p-3 text-sm">عدد وسائل الدخول السريع المسجلة: {passkeys.length}</div>}<Button onClick={registerPasskey} disabled={passkeyLoading} variant="outline"><KeyRound className="size-4"/>{passkeyLoading?"جارٍ التفعيل...":"تفعيل / إضافة جهاز"}</Button></CardContent></Card></div>}
