import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Pencil, Plus, Search, Trash2, Users } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useSchool } from "@/contexts/SchoolContext";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { friendlySupabaseError } from "@/lib/supabase-errors";
export const Route=createFileRoute("/_authenticated/_shell/students")({head:()=>({meta:[{title:"الطلاب | Md School"}]}),component:StudentsPage});
type SectionRow={id:string;name:string;grade_level_id:string}; type StudentRow={id:string;full_name:string;student_number:number;grade_level_id:string;section_id:string};
function StudentsPage(){
 const {grades,activeYear}=useSchool(); const activeGrades=grades.filter(g=>g.academic_year_id===activeYear?.id); const [sections,setSections]=useState<SectionRow[]>([]); const [students,setStudents]=useState<StudentRow[]>([]); const [gradeId,setGradeId]=useState("");const [sectionId,setSectionId]=useState("");const [fullName,setFullName]=useState("");const [search,setSearch]=useState("");const [editId,setEditId]=useState("");
 async function load(){if(!activeYear)return;const [a,b]=await Promise.all([supabase.from("sections").select("id,name,grade_level_id").order("created_at"),supabase.from("student_enrollments").select("student_id,grade_level_id,section_id,students(id,full_name,student_number)").eq("academic_year_id",activeYear.id)]);setSections(a.data??[]);setStudents((b.data??[]).flatMap(r=>{const st=Array.isArray(r.students)?r.students[0]:r.students;return st?[{id:st.id,full_name:st.full_name,student_number:Number(st.student_number),grade_level_id:r.grade_level_id,section_id:r.section_id}]:[]}))}
 useEffect(()=>{void load()},[activeYear?.id]); const availableSections=sections.filter(s=>s.grade_level_id===gradeId); const visible=useMemo(()=>students.filter(s=>(!gradeId||s.grade_level_id===gradeId)&&(!sectionId||s.section_id===sectionId)&&s.full_name.replace(/\s+/g, "").includes(search.trim().replace(/\s+/g, ""))),[students,gradeId,sectionId,search]);
 async function save(){if(!fullName.trim()||!gradeId||!sectionId){toast.error("أكمل اسم الطالب والصف والشعبة");return} if(editId){const {error}=await supabase.from("students").update({full_name:fullName.trim()}).eq("id",editId);if(error){toast.error(friendlySupabaseError(error));return}const {error:moveError}=await supabase.rpc("move_student",{p_student_id:editId,p_year_id:activeYear?.id,p_grade_id:gradeId,p_section_id:sectionId});if(moveError){toast.error(friendlySupabaseError(moveError));return}toast.success("تم تعديل الطالب ونقله")}else{const {error}=await supabase.rpc("add_student_with_enrollment",{p_full_name:fullName.trim(),p_grade_level_id:gradeId,p_section_id:sectionId});if(error){toast.error(friendlySupabaseError(error));return}toast.success("تمت إضافة الطالب")}setFullName("");setEditId("");await load()}
 async function remove(id:string){if(!window.confirm("هل أنت متأكد من حذف هذا الطالب؟ سيؤدي ذلك إلى حذف سجلاته المرتبطة إذا كانت قاعدة البيانات تسمح بذلك."))return;const {error}=await supabase.rpc("delete_student_safely",{p_student_id:id});if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم حذف الطالب");await load()}}
 return <div className="space-y-6"><PageHeader title="الطلاب" description="إضافة وتعديل ونقل وحذف الطلاب مع الحفاظ على رقم الطالب الدائم."/><Card><CardContent className="grid gap-3 pt-6 md:grid-cols-[2fr_1fr_1fr_auto]"><Input value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="اسم الطالب الكامل"/><Select value={gradeId} onValueChange={v=>{setGradeId(v);setSectionId("")}}><SelectTrigger><SelectValue placeholder="الصف"/></SelectTrigger><SelectContent>{activeGrades.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select><Select value={sectionId} onValueChange={setSectionId}><SelectTrigger><SelectValue placeholder="الشعبة"/></SelectTrigger><SelectContent>{availableSections.map(s=><SelectItem key={s.id} value={s.id}>{s.name}</SelectItem>)}</SelectContent></Select><Button onClick={save}><Plus className="size-4"/>{editId?"حفظ التعديل":"إضافة"}</Button></CardContent></Card><Card><CardContent className="pt-6"><div className="relative mb-4 max-w-sm"><Search className="absolute end-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالاسم" className="pe-9"/></div><Table><TableHeader><TableRow><TableHead>رقم الطالب</TableHead><TableHead>الاسم</TableHead><TableHead>الصف</TableHead><TableHead>الشعبة</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visible.map(s=><TableRow key={s.id}><TableCell>{s.student_number}</TableCell><TableCell className="font-medium">{s.full_name}</TableCell><TableCell>{grades.find(g=>g.id===s.grade_level_id)?.name}</TableCell><TableCell>{sections.find(r=>r.id===s.section_id)?.name}</TableCell><TableCell className="text-left"><Button variant="ghost" size="icon" onClick={()=>{setEditId(s.id);setFullName(s.full_name);setGradeId(s.grade_level_id);setSectionId(s.section_id)}}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>void remove(s.id)}><Trash2 className="size-4"/></Button></TableCell></TableRow>)}</TableBody></Table>{visible.length===0&&<div className="py-10 text-center text-muted-foreground"><Users className="mx-auto mb-2 size-7"/>لا يوجد طلاب مطابقون</div>}</CardContent></Card></div>
}
