import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { ArrowDown, ArrowUp, BookMarked, Pencil, Plus, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/common/PageHeader";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useSchool } from "@/contexts/SchoolContext"; import { supabase } from "@/integrations/supabase/client"; import { toast } from "sonner";
import { friendlySupabaseError } from "@/lib/supabase-errors";
export const Route=createFileRoute("/_authenticated/_shell/subjects")({head:()=>({meta:[{title:"المواد | Md School"}]}),component:SubjectsPage});
type SubjectRow={id:string;name:string;grade_level_id:string;sort_order:number};
function SubjectsPage(){const{school,grades,activeYear}=useSchool();const activeGrades=grades.filter(g=>g.academic_year_id===activeYear?.id);const[gradeId,setGradeId]=useState("");const[name,setName]=useState("");const[rows,setRows]=useState<SubjectRow[]>([]);const[editId,setEditId]=useState("");
 async function load(){const{data}=await supabase.from("subjects").select("id,name,grade_level_id,sort_order").order("sort_order");setRows((data??[])as SubjectRow[])}useEffect(()=>{void load()},[]);
 async function save(){if(!school||!gradeId||!name.trim()){toast.error("أكمل الصف واسم المادة");return}const same=rows.filter(r=>r.grade_level_id===gradeId);const payload={school_id:school.id,grade_level_id:gradeId,name:name.trim(),sort_order:editId?(rows.find(r=>r.id===editId)?.sort_order??1):same.length+1};const{error}=editId?await supabase.from("subjects").update(payload).eq("id",editId):await supabase.from("subjects").insert(payload);if(error)toast.error(friendlySupabaseError(error));else{toast.success(editId?"تم تعديل المادة":"تمت إضافة المادة");setName("");setEditId("");await load()}}
 async function remove(id:string){if(!window.confirm("هل أنت متأكد من حذف هذه المادة؟ سيتم رفض الحذف إذا كانت مرتبطة بدرجات."))return;const{error}=await supabase.from("subjects").delete().eq("id",id);if(error)toast.error(friendlySupabaseError(error));else{toast.success("تم حذف المادة");await load()}}
 async function move(id:string,dir:-1|1){const list=rows.filter(r=>r.grade_level_id===gradeId).sort((a,b)=>a.sort_order-b.sort_order);const i=list.findIndex(r=>r.id===id),j=i+dir;if(i<0||j<0||j>=list.length)return;const a=list[i],b=list[j];const {error}=await supabase.rpc("swap_subject_order",{p_subject_id:a.id,p_direction:dir});if(error)toast.error(friendlySupabaseError(error));else await load()}
 const visible=gradeId?rows.filter(r=>r.grade_level_id===gradeId).sort((a,b)=>a.sort_order-b.sort_order):rows;return <div className="space-y-6"><PageHeader title="المواد" description="إضافة وتعديل وحذف وترتيب مواد كل صف."/><Card><CardContent className="grid gap-3 pt-6 sm:grid-cols-[1fr_1fr_auto]"><Select value={gradeId} onValueChange={v=>{setGradeId(v);setEditId("");setName("")}}><SelectTrigger><SelectValue placeholder="اختر الصف"/></SelectTrigger><SelectContent>{activeGrades.map(g=><SelectItem key={g.id} value={g.id}>{g.name}</SelectItem>)}</SelectContent></Select><Input value={name} onChange={e=>setName(e.target.value)} placeholder="اسم المادة"/><Button onClick={save}><Plus className="size-4"/>{editId?"حفظ التعديل":"إضافة"}</Button></CardContent></Card><Card><CardContent className="pt-6"><Table><TableHeader><TableRow><TableHead>الترتيب</TableHead><TableHead>المادة</TableHead><TableHead>الصف</TableHead><TableHead/></TableRow></TableHeader><TableBody>{visible.map((r,i)=><TableRow key={r.id}><TableCell>{r.sort_order}</TableCell><TableCell className="font-medium">{r.name}</TableCell><TableCell>{grades.find(g=>g.id===r.grade_level_id)?.name}</TableCell><TableCell className="text-left"><Button variant="ghost" size="icon" disabled={i===0} onClick={()=>void move(r.id,-1)}><ArrowUp className="size-4"/></Button><Button variant="ghost" size="icon" disabled={i===visible.length-1} onClick={()=>void move(r.id,1)}><ArrowDown className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>{setEditId(r.id);setGradeId(r.grade_level_id);setName(r.name)}}><Pencil className="size-4"/></Button><Button variant="ghost" size="icon" onClick={()=>void remove(r.id)}><Trash2 className="size-4"/></Button></TableCell></TableRow>)}</TableBody></Table>{visible.length===0&&<div className="py-10 text-center text-muted-foreground"><BookMarked className="mx-auto mb-2 size-7"/>لا توجد مواد مطابقة</div>}</CardContent></Card></div>}
