// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';
import { cacheResponse, getCachedResponse, getCurrentUserIdFromJwt, isOffline, queueMutation } from '@/lib/offline-store';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function jwtSubject(authorization: string | null) {
  try {
    if (!authorization?.startsWith("Bearer ")) return getCurrentUserIdFromJwt();
    const payload = authorization.slice(7).split(".")[1];
    return payload ? String(JSON.parse(atob(payload.replace(/-/g, "+").replace(/_/g, "/"))).sub ?? getCurrentUserIdFromJwt()) : getCurrentUserIdFromJwt();
  } catch { return getCurrentUserIdFromJwt(); }
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return async (input, init) => {
    const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) headers.delete('Authorization');
    headers.set('apikey', supabaseKey);

    const request = new Request(input, { ...init, headers });
    const url = request.url;
    const isSupabaseDataRequest = url.includes("/rest/v1/");
    const method = request.method.toUpperCase();
    const userId = jwtSubject(headers.get("Authorization"));
    const cacheKey = `md-offline:${userId}:${url}`;

    if (method === "GET" && isSupabaseDataRequest && isOffline()) {
      const cached = await getCachedResponse(cacheKey);
      if (cached) return cached;
    }

    if (isOffline() && method !== "GET" && isSupabaseDataRequest && !url.includes("/auth/")) {
      const body = await request.clone().text();
      const storedHeaders: Record<string, string> = {};
      request.headers.forEach((value, key) => { storedHeaders[key] = value; });
      await queueMutation({ userId, url, method, headers: storedHeaders, body: body || undefined, createdAt: Date.now() });
      window.dispatchEvent(new CustomEvent("md-school-offline-queued"));
      return new Response(JSON.stringify({ data: null, error: null }), {
        status: 200,
        headers: { "content-type": "application/json", "x-md-school-offline-queued": "true" },
      });
    }

    try {
      const response = await fetch(request);
      if (method === "GET" && isSupabaseDataRequest && response.ok) void cacheResponse(cacheKey, response);
      return response;
    } catch (error) {
      if (method === "GET" && isSupabaseDataRequest) {
        const cached = await getCachedResponse(cacheKey);
        if (cached) return cached;
      }
      throw error;
    }
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
      experimental: { passkey: true },
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

